import { PositionCategory } from '@/types/recruitment';

export const RECRUITMENT_CATEGORIES: PositionCategory[] = [
    {
        id: 'documentation',
        title: 'Documentation',
        description: 'Write clear guides and reports that help the community grow.',
        problems: [
            {
                id: 'doc-001',
                title: 'Write an Onboarding Guide',
                description: 'Create a comprehensive onboarding guide for new members joining the club.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/1',
                categoryId: 'documentation',
            },
            {
                id: 'doc-002',
                title: 'Rewrite an Open Source README',
                description: 'Improve and rewrite an existing open source project README for better clarity.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/2',
                categoryId: 'documentation',
            },
            {
                id: 'doc-003',
                title: 'Post-Event Report',
                description: 'Document a detailed post-event report covering key takeaways and feedback.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/3',
                categoryId: 'documentation',
            },
            {
                id: 'doc-004',
                title: 'One-Page Contribution Guide',
                description: 'Draft a concise one-page guide for contributing to club projects.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/4',
                categoryId: 'documentation',
            },
        ],
    },
    {
        id: 'designing',
        title: 'Designing',
        description: 'Create stunning visuals and brand identity for C³.',
        problems: [
            {
                id: 'des-001',
                title: "Poster for 'Build in Public'",
                description: "Design an eye-catching poster for the 'Build in Public' initiative.",
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/5',
                categoryId: 'designing',
            },
            {
                id: 'des-002',
                title: 'Propose Visual Identity',
                description: 'Propose a cohesive visual identity system including colors, typography, and style.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/6',
                categoryId: 'designing',
            },
            {
                id: 'des-003',
                title: 'GitHub Profile Banner',
                description: 'Design a professional GitHub organization profile banner for C³.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/7',
                categoryId: 'designing',
            },
            {
                id: 'des-004',
                title: 'Instagram Visual – Manifesto Line',
                description: 'Create an Instagram visual featuring the club manifesto line.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/8',
                categoryId: 'designing',
            },
        ],
    },
    {
        id: 'organizing',
        title: 'Organizing',
        description: 'Plan and execute events that bring the community together.',
        problems: [
            {
                id: 'org-001',
                title: 'Plan Zero-Budget Meetup',
                description: 'Design a plan for organizing a meetup with zero budget and maximum impact.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/9',
                categoryId: 'organizing',
            },
            {
                id: 'org-002',
                title: 'Design 48-Hour Sprint Flow',
                description: 'Create a detailed flow for a 48-hour hackathon sprint from start to finish.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/10',
                categoryId: 'organizing',
            },
            {
                id: 'org-003',
                title: 'Speaker Cancelled Crisis Plan',
                description: 'Draft a contingency plan for when a speaker cancels last minute.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/11',
                categoryId: 'organizing',
            },
            {
                id: 'org-004',
                title: 'Map New Member Journey',
                description: "Map out the complete journey of a new member from sign-up to active participation.",
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/12',
                categoryId: 'organizing',
            },
        ],
    },
    {
        id: 'technical',
        title: 'Technical',
        description: 'Build and maintain the technical infrastructure of C³.',
        problems: [
            {
                id: 'tech-001',
                title: 'Static Website Setup',
                description: 'Set up a static website for a club initiative with proper deployment.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/13',
                categoryId: 'technical',
            },
            {
                id: 'tech-002',
                title: 'Auto-Label Overdue Issues',
                description: 'Create a GitHub Action that auto-labels issues when they become overdue.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/14',
                categoryId: 'technical',
            },
            {
                id: 'tech-003',
                title: 'Document Cloud Architecture',
                description: 'Create architecture documentation for the club\'s cloud infrastructure.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/15',
                categoryId: 'technical',
            },
            {
                id: 'tech-004',
                title: 'Form-Free Task Interest System',
                description: 'Build a system to capture task interest without traditional forms.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/16',
                categoryId: 'technical',
            },
        ],
    },
    {
        id: 'socialmedia',
        title: 'Social Media',
        description: 'Grow our presence and engage the community across platforms.',
        problems: [
            {
                id: 'sm-001',
                title: 'Three LinkedIn Posts',
                description: 'Write three professional LinkedIn posts to promote club activities and achievements.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/17',
                categoryId: 'socialmedia',
            },
            {
                id: 'sm-002',
                title: '7-Day Instagram Launch Calendar',
                description: 'Plan a 7-day Instagram content calendar for a product or event launch.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/18',
                categoryId: 'socialmedia',
            },
            {
                id: 'sm-003',
                title: 'Reply to Criticism Comment',
                description: 'Draft a thoughtful, professional reply to a negative comment on social media.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/19',
                categoryId: 'socialmedia',
            },
            {
                id: 'sm-004',
                title: 'Cloud Concept Instagram Carousel',
                description: 'Design an Instagram carousel post explaining a cloud computing concept simply.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/20',
                categoryId: 'socialmedia',
            },
        ],
    },
    {
        id: 'publicity',
        title: 'Publicity',
        description: 'Spread the word and bring more talent into the ecosystem.',
        problems: [
            {
                id: 'pub-001',
                title: '90-Second Classroom Pitch',
                description: 'Prepare a compelling 90-second pitch to recruit members during classroom visits.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/21',
                categoryId: 'publicity',
            },
            {
                id: 'pub-002',
                title: 'Mystery Poster Campaign',
                description: 'Design a mystery poster campaign to create buzz around an upcoming event.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/22',
                categoryId: 'publicity',
            },
            {
                id: 'pub-003',
                title: "Honest 'What\\'s in It for Me' Answer",
                description: "Craft an honest and compelling answer to the question 'What\\'s in it for me?' for potential recruits.",
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/23',
                categoryId: 'publicity',
            },
            {
                id: 'pub-004',
                title: 'Campus Information Map Strategy',
                description: 'Develop a strategy for placing information points across campus to attract new members.',
                githubIssueUrl: 'https://github.com/cloudcommunityclub/Recruitment-2026/issues/24',
                categoryId: 'publicity',
            },
        ],
    },
];
